### ISSUE TITLE
sleep talk not understood

### ISSUE THREAD

**Issue by Kymawave** [pmariglia/foul-play#108]
the bot seems to never use sleep talk in one of my dedicated sleep talk teams. is sleep talk payback calculated correctly? the bot is very keen to use rest, but it then just stays in without switching, using other moves to no effect.

**Comment by pmariglia** [comment]
Yes, sleeptalk is not understood - the bot thinks that the move will do nothing if it is asleep.

Adding logic for this isn't too complicated. I'll see if I can add logic for this.

**Comment by Kymawave** [comment]
stating the obvious here just in case theres problems down the line, it should probably also be made aware that sleep from rest always lasts 2 turns, so it never gambles for a first turn wake-up. it might already, but i wouldnt know lol.

**Comment by pmariglia** [comment]
Almost 3 years later but with the engine refactor in #209 sleeptalk is understood via https://github.com/pmariglia/poke-engine
