### ISSUE TITLE
Fainted Illusion Pokemon (might be known)

### ISSUE THREAD

**Issue by hypersonicstorm** [pmariglia/foul-play#174]
Apologies if this is already known (or if illusion is just too annoying to deal with), but when a pokemon with illusion faints, and the real mon is sent out, the bot seems to break

Edit: this might be an eject button-specific issue since I don't remember the bot crashing to every single zoroak in the past 

![Screenshot_20230830-235514](https://github.com/pmariglia/showdown/assets/73567298/7ba1ee32-8a8b-4cf7-a394-944ed23550d7)
![Screenshot_20230830-235428](https://github.com/pmariglia/showdown/assets/73567298/084097c7-3b62-48b6-b792-56535bbdd865)
![Screenshot_20230830-235358](https://github.com/pmariglia/showdown/assets/73567298/5282e079-e360-4c46-8d7d-6a3ba7d750ac)

**Comment by hypersonicstorm** [comment]
Ok  hisuian zoroak being sent out just seems to break it (might be a hisuian form problem)

![Screenshot_20230831-173142](https://github.com/pmariglia/showdown/assets/73567298/8aa7e25a-58ef-4ff9-b474-11ecc25b7b70)
![Screenshot_20230831-173157](https://github.com/pmariglia/showdown/assets/73567298/75ce1cdf-4512-4acb-a0ea-ed5a2e2e6f38)

**Comment by hypersonicstorm** [comment]
Here's a replay if my explanation was confusing

[Replay](https://replay.pokemonshowdown.com/gen9ou-1934321672)

**Comment by pmariglia** [comment]
Closing this as its been over a year and #209 should account for Zoroark in the sense that the bot should no longer crash when encountering it.

Please re-open if this happens again.
