### ISSUE TITLE
does not understand passers

### ISSUE THREAD

**Issue by jonasrhee1208** [pmariglia/foul-play#195]
when a pokemon has a stat boosting move baton pass and a support move it should be able to passhttps://www.githubstatus.com/

**Comment by pmariglia** [comment]
With #209 this is finally implemented.

Logic to account for baton-passed boosts/volatiles/etc is here in the `switch_or_drag` function: https://github.com/pmariglia/foul-play/blob/3b22d9737756686387025140e6d91423d0df4581/fp/battle_modifier.py#L241
