### ISSUE TITLE
Running Issue:socket.gaierror: [Errno 11001] getaddrinfo failed

### ISSUE THREAD

**Issue by kirillstrelaev4** [pmariglia/foul-play#203]
Output:
> [DEBUG]    Applying move mod for gen 4
> [DEBUG]    Applying dex mod for gen 4
> [DEBUG]    Setting random battle sets for gen 7
> [ERROR]    Traceback (most recent call last):
>   File "c:\Users\User\Desktop\showdown-master\run.py", line 103, in <module>
>     asyncio.run(showdown())
>   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 190, in run
>     return runner.run(main)
>            ^^^^^^^^^^^^^^^^
>   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
>     return self._loop.run_until_complete(task)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 654, in run_until_complete
>     return future.result()
>            ^^^^^^^^^^^^^^^
>   File "c:\Users\User\Desktop\showdown-master\run.py", line 56, in showdown
>     ps_websocket_client = await PSWebsocketClient.create(
>                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "c:\Users\User\Desktop\showdown-master\showdown\websocket_client.py", line 35, in create
>     self.websocket = await websockets.connect(self.address)
>                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\websockets\legacy\client.py", line 650, in __await_impl_timeout__
>     return await asyncio.wait_for(self.__await_impl__(), self.open_timeout)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\tasks.py", line 489, in wait_for
>     return fut.result()
>            ^^^^^^^^^^^^
>   File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\websockets\legacy\client.py", line 654, in __await_impl__
>     transport, protocol = await self._create_connection()
>                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 1046, in create_connection
>     infos = await self._ensure_resolved(
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 1420, in _ensure_resolved
>     return await loop.getaddrinfo(host, port, family=family, type=type,
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 868, in getaddrinfo
>     return await self.run_in_executor(
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\concurrent\futures\thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\socket.py", line 962, in getaddrinfo
>     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> socket.gaierror: [Errno 11001] getaddrinfo failed
> 
> Traceback (most recent call last):
>   File "c:\Users\User\Desktop\showdown-master\run.py", line 103, in <module>
>     asyncio.run(showdown())
>   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 190, in run
>     return runner.run(main)
>            ^^^^^^^^^^^^^^^^
>   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
>     return self._loop.run_until_complete(task)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 654, in run_until_complete
>     return future.result()
>            ^^^^^^^^^^^^^^^
>   File "c:\Users\User\Desktop\showdown-master\run.py", line 56, in showdown
>     ps_websocket_client = await PSWebsocketClient.create(
>                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "c:\Users\User\Desktop\showdown-master\showdown\websocket_client.py", line 35, in create
>     self.websocket = await websockets.connect(self.address)
>                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\websockets\legacy\client.py", line 650, in __await_impl_timeout__
>     return await asyncio.wait_for(self.__await_impl__(), self.open_timeout)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\tasks.py", line 489, in wait_for
>     return fut.result()
>            ^^^^^^^^^^^^
>   File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\websockets\legacy\client.py", line 654, in __await_impl__
>     transport, protocol = await self._create_connection()
>                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 1046, in create_connection
>     infos = await self._ensure_resolved(
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 1420, in _ensure_resolved
>     return await loop.getaddrinfo(host, port, family=family, type=type,
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 868, in getaddrinfo
>     return await self.run_in_executor(
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\concurrent\futures\thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\socket.py", line 962, in getaddrinfo
>     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> socket.gaierror: [Errno 11001] getaddrinfo failed

env:

> BATTLE_BOT=safest
> WEBSOCKET_URI=wss://sim3.psim.us/showdown/websocket
> PS_USERNAME=-Removed-
> PS_PASSWORD=-Removed
> BOT_MODE=CHALLENGE_USER
> POKEMON_MODE=gen4ubers
> RUN_COUNT=1
> 
> USER_TO_CHALLENGE=-Removed-
> TEAM_NAME=gen4/ubers/offence
> SAVE_REPLAY=False

I am doing something wrong?

**Comment by pmariglia** [comment]
Looks like you're doing everything right. Was this an intermittent issue or does it consistently not work? It seems like it may be your internet connection

**Comment by Hosea-MP** [comment]
@pmariglia do you have a discord account or server that I can contact you at?

**Comment by pmariglia** [comment]
Closing this. Feel free to re-open if you have some more information about what's going on.
