### ISSUE TITLE
Wrong Gamemode

### ISSUE THREAD

**Issue by DomenJansa** [pmariglia/foul-play#208]
Basically what the title suggests the bot is capable of playing Gen9Nationaldex but I would like to get it to play Gen 9NetionaldexUbers. When you make the bot queue for this game mode it searches for "https://www.smogon.com/stats/2024-11/chaos/nationaldex-0.json" Instead of "https://www.smogon.com/stats/2024-11/chaos/gen9nationaldexubers-0.json" that it needs so it just crashes. So I am asking how would i go About adding this Gamemode?

**Comment by pmariglia** [comment]
I am unable to reproduce, I am getting `gen9nationaldexubers-0.json` when i try this. 

This may have been fixed with #209 since I see you opened this before I merged that in - can you confirm whether or not this is still an issue?

**Comment by DomenJansa** [comment]
Yeah Sorry I have been away from home for a while so I havent been able to
test it since the "update" lol. I will try it as soon As I can.

Thanks for the Bot BTW I love it.


V V sob., 28. dec. 2024 ob 18:36 je oseba pmariglia <
***@***.***> napisala:

**Comment by DomenJansa** [comment]
Ok so I have tried again now with the updated code and the problem is gone. So its all good and working. Further more i have discovered that Megas work just fine However the bot Mega evolves fist chance they get witch is pretty reasonable. Z moves also seem to work. But the Ai shoots them whenever they get the ability to shoot a move of corresponding type. so If it thinks using surf is the best move it will use a Z move if available no matter whether or not its *optimal*.  But overall it has satisfiying performance even in gen9nationaldexUbers format Despite it being not fully supported.  Thank you again for the Bot
